## 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def division(a,b):
    return a/b
try: 
    division(5,0)
except ZeroDivisionError as ze:
    print("we can't divide by zero")
except:
    print("other error")

we can't divide by zero


## 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
## Hint: Subject,Verb and Object should be declared in the program as shown below.
## subjects=["Americans ","Indians"]
## verbs=["play","watch"]
## objects=["Baseball","Cricket"]

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
l=[(i+" "+j+" "+k) for i in subjects for j in verbs for k in objects]
for m in l:
    print(m)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


##                                                           OR

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## 3. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
## HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [5]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.vander(x,3)
print(y)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


## OR

In [7]:
n=int(input())
np.column_stack([x**(n-1-i) for i in range(n)])

3


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

## END